// Mocks generated by Mockito 5.4.6 from annotations
// in cric_snap/test/quick_match_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cric_snap/innings/model.dart' as _i5;
import 'package:cric_snap/match/model.dart' as _i4;
import 'package:cric_snap/services/quick_match_data_source.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQuickTeamResolution_0 extends _i1.SmartFake
    implements _i2.QuickTeamResolution {
  _FakeQuickTeamResolution_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuickMatchDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuickMatchDataSource extends _i1.Mock
    implements _i2.QuickMatchDataSource {
  MockQuickMatchDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> nextQuickMatchNumber() =>
      (super.noSuchMethod(
            Invocation.method(#nextQuickMatchNumber, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i2.QuickTeamResolution> getOrCreateQuickTeam({
    required String? teamName,
    required String? abbreviation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateQuickTeam, [], {
              #teamName: teamName,
              #abbreviation: abbreviation,
            }),
            returnValue: _i3.Future<_i2.QuickTeamResolution>.value(
              _FakeQuickTeamResolution_0(
                this,
                Invocation.method(#getOrCreateQuickTeam, [], {
                  #teamName: teamName,
                  #abbreviation: abbreviation,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.QuickTeamResolution>);

  @override
  _i3.Future<void> insertMatch(_i4.MatchModel? match) =>
      (super.noSuchMethod(
            Invocation.method(#insertMatch, [match]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertInnings(_i5.Innings? innings) =>
      (super.noSuchMethod(
            Invocation.method(#insertInnings, [innings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
